services:
  mongo:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - vidnest-network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGODB_URL=mongodb://mongo:27017/vidnest
      - CORS_ORIGIN=*
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRY=1d
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRY=10d
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mongo
    networks:
      - vidnest-network

volumes:
  mongo-data:

networks:
  vidnest-network:
    driver: bridge